Mug:
  CounterTop: 0.95
  DiningTable: 0.80
  Sink: 0.75
  CoffeeTable: 0.70
  Cabinet: 0.65
  SideTable: 0.55
  Shelf: 0.45
  Drawer: 0.40
  Fridge: 0.25
Bowl:
  CounterTop: 0.90
  DiningTable: 0.85
  Cabinet: 0.75
  Sink: 0.65
  CoffeeTable: 0.60
  Shelf: 0.45
  SideTable: 0.40
  Drawer: 0.35
  Fridge: 0.25
RemoteControl:
  Shelf: 0.55
  Cabinet: 0.45
  Drawer: 0.45
  CounterTop: 0.40
  Sink: 0.15
  Fridge: 0.10
Towel:
  Sink: 0.80
  Cabinet: 0.65
  Drawer: 0.50
  Shelf: 0.45
  CounterTop: 0.35
  Fridge: 0.15
Book:
  Shelf: 0.90
  CounterTop: 0.65
  CoffeeTable: 0.65
  DiningTable: 0.60
  Cabinet: 0.55
  SideTable: 0.55
  Drawer: 0.50
  Fridge: 0.10
  Sink: 0.05
